import { ElementData } from '../types';

export const ELEMENTS_DATA: ElementData[] = [
  { atomicNumber: 1, symbol: 'H', name: 'Hydrogen', group: 1, period: 1, category: 'Reactive Nonmetal' },
  { atomicNumber: 2, symbol: 'He', name: 'Helium', group: 18, period: 1, category: 'Noble Gas' },
  { atomicNumber: 3, symbol: 'Li', name: 'Lithium', group: 1, period: 2, category: 'Alkali Metal' },
  { atomicNumber: 4, symbol: 'Be', name: 'Beryllium', group: 2, period: 2, category: 'Alkaline Earth Metal' },
  { atomicNumber: 5, symbol: 'B', name: 'Boron', group: 13, period: 2, category: 'Metalloid' },
  { atomicNumber: 6, symbol: 'C', name: 'Carbon', group: 14, period: 2, category: 'Reactive Nonmetal' },
  { atomicNumber: 7, symbol: 'N', name: 'Nitrogen', group: 15, period: 2, category: 'Reactive Nonmetal' },
  { atomicNumber: 8, symbol: 'O', name: 'Oxygen', group: 16, period: 2, category: 'Reactive Nonmetal' },
  { atomicNumber: 9, symbol: 'F', name: 'Fluorine', group: 17, period: 2, category: 'Reactive Nonmetal' },
  { atomicNumber: 10, symbol: 'Ne', name: 'Neon', group: 18, period: 2, category: 'Noble Gas' },
  { atomicNumber: 11, symbol: 'Na', name: 'Sodium', group: 1, period: 3, category: 'Alkali Metal' },
  { atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', group: 2, period: 3, category: 'Alkaline Earth Metal' },
  { atomicNumber: 13, symbol: 'Al', name: 'Aluminium', group: 13, period: 3, category: 'Post-transition Metal' },
  { atomicNumber: 14, symbol: 'Si', name: 'Silicon', group: 14, period: 3, category: 'Metalloid' },
  { atomicNumber: 15, symbol: 'P', name: 'Phosphorus', group: 15, period: 3, category: 'Reactive Nonmetal' },
  { atomicNumber: 16, symbol: 'S', name: 'Sulfur', group: 16, period: 3, category: 'Reactive Nonmetal' },
  { atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', group: 17, period: 3, category: 'Reactive Nonmetal' },
  { atomicNumber: 18, symbol: 'Ar', name: 'Argon', group: 18, period: 3, category: 'Noble Gas' },
  { atomicNumber: 19, symbol: 'K', name: 'Potassium', group: 1, period: 4, category: 'Alkali Metal' },
  { atomicNumber: 20, symbol: 'Ca', name: 'Calcium', group: 2, period: 4, category: 'Alkaline Earth Metal' },
  { atomicNumber: 21, symbol: 'Sc', name: 'Scandium', group: 3, period: 4, category: 'Transition Metal' },
  { atomicNumber: 22, symbol: 'Ti', name: 'Titanium', group: 4, period: 4, category: 'Transition Metal' },
  { atomicNumber: 23, symbol: 'V', name: 'Vanadium', group: 5, period: 4, category: 'Transition Metal' },
  { atomicNumber: 24, symbol: 'Cr', name: 'Chromium', group: 6, period: 4, category: 'Transition Metal' },
  { atomicNumber: 25, symbol: 'Mn', name: 'Manganese', group: 7, period: 4, category: 'Transition Metal' },
  { atomicNumber: 26, symbol: 'Fe', name: 'Iron', group: 8, period: 4, category: 'Transition Metal' },
  { atomicNumber: 27, symbol: 'Co', name: 'Cobalt', group: 9, period: 4, category: 'Transition Metal' },
  { atomicNumber: 28, symbol: 'Ni', name: 'Nickel', group: 10, period: 4, category: 'Transition Metal' },
  { atomicNumber: 29, symbol: 'Cu', name: 'Copper', group: 11, period: 4, category: 'Transition Metal' },
  { atomicNumber: 30, symbol: 'Zn', name: 'Zinc', group: 12, period: 4, category: 'Transition Metal' },
];